In [56]:
import kagglehub
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

# Download latest version
path = kagglehub.dataset_download("jayaantanaath/student-habits-vs-academic-performance")

print("Path to dataset files:", path)

DATA_DIR = Path("..") / "data"
file_path = DATA_DIR / "student_habits_performance.csv"

from kagglehub import KaggleDatasetAdapter

file_path = "student_habits_performance.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "jayaantanaath/student-habits-vs-academic-performance",
  file_path,)

Path to dataset files: /Users/tiana/.cache/kagglehub/datasets/jayaantanaath/student-habits-vs-academic-performance/versions/1


/var/folders/fm/zzjr3l5d7nl5vdp9q79tzwvh0000gn/T/ipykernel_10330/1721510207.py:20: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(


In [57]:
print("Shape:", df.shape)
df.head()

Shape: (1000, 16)


,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4


In [59]:
series_genders = df.groupby('gender').count()

sns.set(style="whitegrid") 


plt.figure(figsize=(10, 6))  
bar_plot = sns.barplot(x=series_genders.index, 
                 y=series_genders, 
                 palette='pastel', 
                 edgecolor='black',  
                 linewidth=1.5) 


plt.title('Gender Distribution', fontsize=16, weight='bold')  
plt.xlabel('Gender', fontsize=14)
plt.ylabel('Number of People', fontsize=14)


plt.xticks(rotation=0, fontsize=12)  
plt.yticks(fontsize=12)  

for p in bar_plot.patches:
    bar_plot.annotate(format(p.get_height(), '.0f'), 
                      (p.get_x() + p.get_width() / 2., p.get_height()), 
                      ha='center', va='center', fontsize=12, 
                      color='black', xytext=(0, 10), textcoords='offset points')

plt.tight_layout()
plt.show()

ValueError: Data must be 1-dimensional, got ndarray of shape (3, 15) instead

<Figure size 1000x600 with 0 Axes>

In [38]:
missing_val = df.isnull().sum()
print("missing values in each column:")
print(missing_val)

missing values in each column:
student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64


In [39]:
# got from kaggle
df['parental_education_level'] = df['parental_education_level'].fillna(df['parental_education_level'].mode()[0])

In [40]:
missing_val = df.isnull().sum()
print("missing values in each column:")
print(missing_val)

missing values in each column:
student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64


In [41]:
df["gender"].unique()
df["gender"] = df["gender"].str.strip().str.title()

gender_map = {
    "Male": 0,
    "Female": 1,
    "Other": 2
}

df["gender"] = df["gender"].map(gender_map)

In [42]:
df["gender"].unique()

array([1, 0, 2])

In [43]:
df["diet_quality"].unique()
df["diet_quality"] = df["diet_quality"].str.strip().str.title()

diet_map = {
    "Poor": 0,
    "Fair": 1,
    "Good": 2
}

df["diet_quality"] = df["diet_quality"].map(diet_map)

In [44]:
df["diet_quality"].unique()

array([1, 2, 0])

In [45]:
df["parental_education_level"].unique()
df["parental_education_level"] = df["parental_education_level"].str.strip().str.title()

paredlev_map = {
    "High School": 0,
    "Bachelor": 1,
    "Master": 2
}

df["parental_education_level"] = df["parental_education_level"].map(paredlev_map)

In [46]:
df["parental_education_level"].unique()

array([2, 0, 1])

In [47]:
df["internet_quality"].unique()
df["internet_quality"] = df["internet_quality"].str.strip().str.title()

internet_map = {
    "Poor": 0,
    "Average": 1,
    "Good": 2
}

df["internet_quality"] = df["internet_quality"].map(internet_map)

In [48]:
df["internet_quality"].unique()

array([1, 0, 2])

In [49]:
df["extracurricular_participation"].unique()
df["extracurricular_participation"] = df["extracurricular_participation"].str.strip().str.title()

clubs_map = {
    "No": 0,
    "Yes": 1
}

df["extracurricular_participation"] = df["extracurricular_participation"].map(clubs_map)

In [50]:
df["extracurricular_participation"].unique()

array([1, 0])

In [ ]:
labels = ['Young', 'Middle-aged', 'Elderly']
bins = [18, 30, 50, 70]
df['Age_Group'] = pd.cut(df.Age, bins=bins, labels=labels, right=False)


plt.figure(figsize=(15, 12))


plt.subplot(2, 1, 1)
sns.kdeplot(x='Age', data=df,
            fill=True,
            color='royalblue',
            linewidth=2,
            alpha=0.7)


plt.title('Age Distribution in the City (KDE Plot)', fontsize=16, fontweight='bold')
plt.xlabel('Age', fontsize=14)
plt.ylabel('Frequency', fontsize=14)

mean_age = df.Age.mean()

xticks = list(range(0, 91, 10)) + [mean_age] 
plt.xticks(xticks)
plt.axvline(x=mean_age, color='red', linestyle='--', label='Mean', alpha=0.5)


plt.grid(True, linestyle='--', alpha=0.5)
plt.legend()


plt.tight_layout()

plt.subplot(2,1,2)

ax = sns.countplot(x='Age_Group', data=df, palette='coolwarm', edgecolor='black', linewidth=1.5)


plt.title('Age Group Distribution', fontsize=16, fontweight='bold')
plt.xlabel('Age Group', fontsize=14)
plt.ylabel('People per Group', fontsize=14)


for p in ax.patches:
    ax.annotate(f'{p.get_height()}', 
                (p.get_x() + p.get_width() / 2., p.get_height()), 
                ha='center', va='center', 
                fontsize=12, color='black', 
                xytext=(0, 9), textcoords='offset points')


plt.xticks(fontsize=12)


plt.tight_layout()

plt.show()

In [ ]:
df_cleaned = df.select_dtypes(include=['number']).dropna()
plt.figure(figsize=(12, 6))
sns.heatmap(df_cleaned.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define bins and labels
co2_bins = [0, 11, 30, np.inf]
labels = ["Target", "Average", "Worrisome"]

# Create Carbon Footprint Category
df["CO2_Category"] = pd.cut(
    df["Carbon_Footprint_kgCO2"],
    bins=co2_bins,
    labels=labels,
    right=False
)

# Create figure
plt.figure(figsize=(15, 12))

# =======================
# 1️⃣ KDE Plot
# =======================
plt.subplot(2, 1, 1)

sns.kdeplot(
    x="Carbon_Footprint_kgCO2",
    data=df,
    fill=True,
    color="seagreen",
    linewidth=2,
    alpha=0.7
)

plt.title("Carbon Footprint Distribution (KDE Plot)", fontsize=16, fontweight="bold")
plt.xlabel("Carbon Footprint (kg CO2)", fontsize=14)
plt.ylabel("Density", fontsize=14)

mean_co2 = df["Carbon_Footprint_kgCO2"].mean()

xticks = list(range(0, int(df["Carbon_Footprint_kgCO2"].max()) + 10, 10)) + [mean_co2]
plt.xticks(xticks)

plt.axvline(x=mean_co2, color="red", linestyle="--", label="Mean", alpha=0.6)

plt.grid(True, linestyle="--", alpha=0.5)
plt.legend()

plt.tight_layout()

# =======================
# 2️⃣ Count Plot
# =======================
plt.subplot(2, 1, 2)

ax = sns.countplot(
    x="CO2_Category",
    data=df,
    palette="coolwarm",
    edgecolor="black",
    linewidth=1.5
)

plt.title("Carbon Footprint Category Distribution", fontsize=16, fontweight="bold")
plt.xlabel("CO2 Category", fontsize=14)
plt.ylabel("Number of Individuals", fontsize=14)

# Add value labels on bars
for p in ax.patches:
    ax.annotate(
        f"{p.get_height()}",
        (p.get_x() + p.get_width() / 2., p.get_height()),
        ha="center",
        va="center",
        fontsize=12,
        color="black",
        xytext=(0, 9),
        textcoords="offset points"
    )

plt.xticks(fontsize=12)

plt.tight_layout()
plt.show()

In [ ]:
# Drop missing values
co2_data = df.dropna(subset=["CO2_Category", "Carbon_Footprint_kgCO2"])

# Group by CO2 category
co2_groups = co2_data.groupby("CO2_Category")["Carbon_Footprint_kgCO2"]

# Create figure
fig, ax = plt.subplots(figsize=(10, 6))

co2_data.boxplot(
    column="Carbon_Footprint_kgCO2",
    by="CO2_Category",
    ax=ax,
    grid=False,
    patch_artist=True,
    boxprops=dict(facecolor="lightgreen", color="green"),
    medianprops=dict(color="red"),
    whiskerprops=dict(color="green"),
    capprops=dict(color="green"),
    flierprops=dict(markerfacecolor='gray',
                    marker='o',
                    markersize=5,
                    linestyle='none')
)

# Optional: Calculate summary statistics (like your example)
for i, (category, group) in enumerate(co2_groups):
    mean = group.mean()
    std = group.std()
    min_val = group.min()
    max_val = group.max()
    print(f"{category}:")
    print(f"  Mean: {mean:.2f}")
    print(f"  Std: {std:.2f}")
    print(f"  Min: {min_val:.2f}")
    print(f"  Max: {max_val:.2f}")
    print("-" * 30)

# Labels
ax.set_title("Carbon Footprint by CO2 Category")
ax.set_xlabel("CO2 Category")
ax.set_ylabel("Carbon Footprint (kg CO2)")

plt.suptitle("")  # Remove automatic subtitle
plt.show()

In [ ]:
# Drop missing values
steps_df = df.dropna(subset=["Steps_Walked", "Carbon_Footprint_kgCO2"])

plt.figure(figsize=(10, 6))

sns.regplot(
    x="Steps_Walked",
    y="Carbon_Footprint_kgCO2",
    data=steps_df,
    scatter_kws={"alpha": 0.5},
    line_kws={"color": "red"}
)

plt.title("Carbon Footprint vs Steps Walked", fontsize=14, fontweight="bold")
plt.xlabel("Steps Walked")
plt.ylabel("Carbon Footprint (kg CO2)")

plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()